### ISSUE TITLE
Directory plugins refers to github>rack>plugins ?

### ISSUE THREAD

**Issue by 2johjoh2** [cschol/vcv-plugindownloader#1]
Just to make sure, when you refer to running the script in the plugins directory, you mean the plugins directory that resides under the github>rack dir ?
Not to be confused with the Documents>Rack directory (for the non-dev version).
(which normally contains all plug binaries)

**Comment by cschol** [comment]
For binary downloads only, I don't think it matters. Either directory should work. 

**However**, if you are using the "-s" ("--source") option to fall back to compiling modules that do not have binary releases, you **must** run the script from the "github>rack" dir, e.g. `~/source/Rack/plugins`, since the build process requires access to files from the source tree.

I will clarify this in the README.

**Comment by cschol** [comment]
Updated README.md in 4a20c12c4d59498142c387090ac3bef72b842886.
